svn:
    # SVN repository URL
    repo_url: http://10.216.1.183/svn

    # target:
    # You have a choice of:
    # trunk, branches/<branch-name>, tags/<tag-name>
    target: trunk

    # tool:
    # You have a choice of:
    # svn, git-svn
    tool: git-svn

    # workspace:
    # Projects will be checked out to the <workspace> directory
    workspace: src

    # projects:
    # The following projects will be checked out from repository
    projects:
    - deployment
    - liboais
    - libobroker
    - libodbaccess
    - libodbparser
    - libodictionary
    - liboheartbeat
    - liboproto
    - libosocket
    - liboutility
    - oalert
    - oanalysis
    - ocoastwatcher
    - odboffline
    - odbreader
    - odbwriter
    - odisplay
    - ofence
    - ofurunoais
    - ogateway
    - omsa-new
    - oplayer
    - oreplay
    - oreplaymanager
    - osquire
    - osysmgt
    - otraining
    - otrgmanager

build:
    # build_type:
    # <build_type> is passed to CMake phase. Choose one of the following options:
    # Debug, Release, RelWithDebInfo
    build_type: Debug

    # build_dir:
    # All projects will be built under <build_dir> directory.
    build_dir: build

    # order
    # Orchid project will be built in the following order.
    order:
    - liboutility
    - liboproto
    - liboais
    - libobroker
    - libodbaccess
    - libodbparser
    - libodictionary
    - liboheartbeat
    - libosocket
    - oalert
    - oanalysis
    - ocoastwatcher
    - odboffline
    - odbreader
    - odbwriter
    - ofence
    - ofurunoais
    - ogateway
    - omsa-new
    - oplayer
    - oreplay
    - oreplaymanager
    - osquire
    - osysmgt
    - otraining
    - otrgmanager

database:
    host: localhost
    port: 5432
    db_name: orchid
    db_user: postgres

test:
    amq_bin_path: apache-activemq-5.5.1-fuse-03-06/bin

    order:
    - odbreader
    - odbwriter
    - osysmgt
    - oalert
    - oanalysis
    - ofence
    - omsa
    - oreplaymanager
    - oplayer

    log_dir: logs
